### ISSUE TITLE
 用paging 分页 后。如何跳转到指定item

### ISSUE THREAD

**Issue by superbor** [qingmei2/blogs#26]
你好最近在用paging 做分页！
用在聊天消息上，现在有需求是，有人回复当前用户会弹出一个按钮。 点击按钮 滚动到这条回复消息。
由于paging 是一页一页加载的，现在无法确定 回复的那条消息的position，无法用ScrollToPosition 。请问有什么办法吗？

**Comment by qingmei2** [comment]
这个详细的需求我暂时也没有什么思路，建议阅读源码找找答案呢。 🤝
