### ISSUE TITLE
关于纠错的纠错

### ISSUE THREAD

**Issue by drogbababa** [qingmei2/blogs#29]
作者您好，看了您的《反思View的Measure过程》，很有帮助。
另外，我认为《关于纠错.md》的最后一行，『臂助』应改为『帮助』。纯属鸡蛋里挑骨头，请别介意。

**Comment by qingmei2** [comment]
@drogbababa 

有趣的issue标题，同样很有趣的内容。

感谢您的建议，我特此专门百度了一下，但还是不太了解【臂助】和【帮助】的区别，在我的这句话中，有什么问题吗？

> 这都将是对开源精神本身很大的 **臂助**。

真诚的讨教，期待您的回复。:smile:

**Comment by drogbababa** [comment]
> @drogbababa
> 
> 有趣的issue标题，同样很有趣的内容。
> 
> 感谢您的建议，我特此专门百度了一下，但还是不太了解【臂助】和【帮助】的区别，在我的这句话中，有什么问题吗？
> 
> > 这都将是对开源精神本身很大的 **臂助**。
> 
> 真诚的讨教，期待您的回复。😄

作者您好，我百度了一下，发现确有『臂助』的用法，我以为是错别字呢，见笑了啊哈哈哈。我会认真读您的文章的~~
[臂助](https://baike.baidu.com/item/%E8%87%82%E5%8A%A9/5873907?fr=aladdin)

**Comment by zjxuzhj** [comment]
哈哈哈。有心就行
